IndexHome/urls.py
from django.urls import path
from . import views

app_name = 'IndexHome'


urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'check-user/', views.check_user, name="check_user"),
    path(r'verify/<str:mail_hash>/<int:id>/', views.verify,name="verify"),
    path(r'verify/<str:mail_hash>/<int:acc_id>/?request_otp=<str:request_otp>',views.resend_otp, name="verify_resend"),
    path(r'account/login/', views.signin, name="signin"),
    path(r'account/create/', views.signup, name="signup"),
    path(r'account/logout/', views.logout, name="logout"),
    path(r'account/forgot/', views.forgot, name="forgot"),
    path(r'account/forgot/verify', views.forgot_final, name="forgot_final"),
    path(r'playground/', views.playground_timer, name="playground"),
    path(r'subscribe-newsletter/',views.newsletter,name="newsletter"),
    path(r'privacy-policy/',views.privacyPolicy,name="privacy"),
    path(r'contact-us/',views.contact,name="contact"),
    path(r'terms-of-service/',views.termsofService,name="termsofService")
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import HomeView, ArticleDetailView, like_sys, PostByTags, PostByCategory,SearchView
app_name = "blog"
urlpatterns = [
    path('', HomeView.as_view(), name="index"),
    path(r'article/<int:pk>', ArticleDetailView.as_view(), name="blog_details"),
    path(r'like/', like_sys, name="like"),
    path(r'tag/<tag_slug>', PostByTags.as_view(), name='post_list_by_tags'),
    path(r'search/', SearchView.as_view(), name='search_qu'),
    path(r'category/<category_slug>',cache_page(1800)(PostByCategory.as_view()),name="category"),
]

caffeinecode/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import handler500,handler404

urlpatterns = [
    path(r'',include('IndexHome.urls')),
    path(r'admin/', admin.site.urls),
    path(r'blog/',include('blog.urls')),
    path(r'hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path(r'api-auth/', include('rest_framework.urls')),
    path(r'projects/',include("projects.urls")),
    path(r'config/',include("Config.urls")),

]
handler500 = "Config.views.handler500"
handler404 = "Config.views.handler404"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

projects/urls.py
from django.urls import path
from . import views
app_name = "projects"

urlpatterns = [
    path(r'',views.index, name="index")
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

projects/views.py
from django.shortcuts import redirect, render
from blog.models import Post

import json


def index(request):
    blog = Post.objects.all()[:3]
    return render(request,"projects/index.html",{"post":blog,'redirect_url':request.get_full_path()})

templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <title>{% block title %}{% endblock title %}</title>
        <meta content="" name="description" />
        <meta content="" name="keywords" />
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'IndexHome/assets/img/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'IndexHome/assets/img/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'IndexHome/assets/img/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'IndexHome/assets/img/site.webmanifest' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet"/>
        {% block styling %}
        {% endblock styling %}
        <link href="{% static 'IndexHome/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'IndexHome/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet"/>
        <link href="{% static 'IndexHome/assets/vendor/aos/aos.css' %}" rel="stylesheet"/>
        <link href="{% static 'IndexHome/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'IndexHome/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'IndexHome/assets/css/style.css' %}" rel="stylesheet"/>
        <script src="{% static 'IndexHome/assets/js/core/jquery.min.js' %}"></script>
        <style>
            body {
                font-family: "Nunito", sans-serif;
                color: #444444;
            }
        </style>
    </head>
    <body id="bodyscroll">
        <!--<div class="loader">
            <div></div>
            </div>-->
        <header id="header" class="header fixed-top">
            <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
                <a href="{% url 'IndexHome:index' %}" class="logo d-flex align-items-center">
                <span id="LogoText">CaffeineCode</span>
                </a>
                <nav id="navbar" class="navbar">
                    <ul>
                        <li><a class="nav-link scrollto" href="{% url 'IndexHome:index' %}">Home</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'IndexHome:index' %}#about">About Us</a></li>
                        <li><a class="nav-link scrollto active" href="{% url 'projects:index' %}">Projects</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'IndexHome:playground' %}">Playground</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'blog:index' %}">Blog</a></li>
                        <li><a class="nav-link scrollto" href="#contact">Contact {{is_login}}</a></li>
                        {% if user.is_authenticated and user.is_active %}
                            <li><a href="{% url 'IndexHome:logout' %}" role="button" class="getstarted scrollto" style="background: rgb(212, 77, 77)">Logout</a></li>
                            <li><a class="getstarted scrollto" role="button">{{ user.username }}</a></li>
                        {% else %}
                            <li><a class="getstarted scrollto" role="button" href="{% url 'IndexHome:signin' %}?redirect-url={{redirect_url}}">Sign In</a></li>
                        {% endif %}
                    </ul>
                    <i class="bi bi-list mobile-nav-toggle"></i>
                </nav>
            </div>
        </header>
        {% block hero %}
        {% endblock hero %}
        <main id="main" style="margin-top: 80px">
            <section id="blog" class="blog">
                {% block search_block %} 
                {% endblock search_block %} 
                {% block explore %}
                {% endblock explore %} 
                {% block owl %} 
                {% endblock owl %} 
                {% block social-btn %}
                {% endblock social-btn %}
                <div class="container" data-aos="fade-up">
                    {% block title_post %}
                    {% endblock title_post %}
                    <div class="row">
                        <div class="col-lg-8 entries">
                            {% block article %}
                            {% endblock article %}
                            <div class="blog-pagination mb-5">
                                <ul class="justify-content-center">
                                    {% block pagination %}
                                    {% endblock pagination %}
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-4" class="sidebar-col">
                            {% block sidebar %}
                            {% endblock sidebar %}
                        </div>
                    </div>
                </div>
            </section>
            {% block recent %} 
            {% endblock recent %}
        </main>
        <footer id="footer" class="footer" >
            <section class="hero d-flex flex-column" style="background:none;padding-bottom:0px;">
                <div class="footer-newsletter">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-12 text-center">
                                <h4>Our Newsletter</h4>
                                <p>
                                    Receive regular updates and announcement by subscibing to our Newsletter
                                </p>
                            </div>
                            <div class="col-lg-6">
                                <form action="{% url 'IndexHome:newsletter' %}" method="post">
                                    {% csrf_token %}
                                    <input type="email" id="letter" name="newsletter" required /><input type="submit" class="enableOnInput" value="Subscribe"/>
                                </form>
                                <div id="error"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <style>
                    .footer .footer-top{
                    background-image: url("{% static 'IndexHome/assets/img/footerbg.webp' %}");
                    background-size: cover;
                    background-repeat: no-repeat;
                    }
                </style>
                <div class="footer-top">
                    <center>
                        <hr style="width:80%;color:#8ba4b1;margin-bottom:45px;">
                    </center>
                    <div class="container">
                        <div class="row justify-content-between">
                            <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6 mt-4 mb-4">
                                <a href="{% url 'IndexHome:index' %}" class="logo d-flex align-items-center">
                                <img src="{% static 'IndexHome/assets/img/logo.svg' %}" style="height:120px;width:120px;">
                                </a>
                                <div class="social-links mt-5" style="text-align: left;">
                                    <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                                    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                                    <a href="#" class="instagram"><i class="bi bi-instagram bx bxl-instagram"></i></a>
                                    <a href="#" class="linkedin"><i class="bi bi-linkedin bx bxl-linkedin"></i></a>
                                </div>
                            </div>
                            <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6 footer-links">
                                <h4>Useful Links</h4>
                                <ul>
                                    <li><a href="{% url 'IndexHome:index' %}">Home</a></li>
                                    <li><a href="{% url 'IndexHome:index' %}#about">About us</a></li>
                                    <li><a href="{% url 'IndexHome:index' %}#contact">Contact us</a></li>
                                    <li><a href="#">Terms of service</a></li>
                                    <li><a href="{% url 'IndexHome:privacy' %}">Privacy policy</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-2 col-6 footer-links">
                                <h4>Our Services</h4>
                                <ul>
                                    <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                                    <li><a href="{% url 'projects:index' %}">Projects</a></li>
                                    <li><a href="{% url 'IndexHome:playground' %}">Playground</a></li>
                                </ul>
                            </div>
                            <div class="col-xl-3 col-lg-2 col-md-4 col-sm-6 footer-contact text-center text-md-start">
                                <h4>Contact Us</h4>
                                <p>
                                    A108 Adam Street <br />
                                    New York, NY 535022<br />
                                    United States <br /><br />
                                    <strong>Phone:</strong> +1 5589 55488 55<br />
                                    <strong>Email:</strong> helpdeveloper.r@gmail.com<br />
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="copyright">
                                    &copy; Copyright 2022 All Rights Reserved | This website is crafted with ❤️ by Rushi
                                </div>
                            </div>
                            <div class="col">
                                <div class="credits">
                                    Possibly used Front-end part of <a href="https://bootstrapmade.com/">BootstrapMade</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </footer>
        <!--<script>
            $(window).on('load',function(){
                $(".loader").fadeOut(1100);
                $(".content").fadeIn(1100);
            });
            </script>-->
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
        <script src="{% static 'IndexHome/assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'IndexHome/assets/vendor/aos/aos.js' %}"></script>
        <script src="{% static 'IndexHome/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'IndexHome/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'IndexHome/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'IndexHome/assets/js/main.js' %}"></script>
        <script src="{% static 'IndexHome/assets/js/utils.js' %}"></script>
        {% block script %} 
        {% endblock script %}
    </body>
</html>

templates/projects/index.html
{% extends 'projects/base.html' %} {% block title %}CaffeineCode - Projects
{%endblock title %} {% block hero %} {% load static %}
<section id="hero" class="hero d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center">
        <h1 data-aos="fade-up">Projects</h1>
        <h2 data-aos="fade-up" data-aos-delay="400">
          Dive in our small crafted projects
        </h2>
        <div data-aos="fade-up" data-aos-delay="600">
          <div class="text-center text-lg-start">
            {% if request.user.is_authenticated %}
            <a
              href="#explore"
              class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center"
            >
              <span>Explore!</span>
              <i class="bi bi-arrow-right"></i>
            </a>
            {% else %}
            <a
              href="{% url 'IndexHome:signup' %}"
              class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center"
            >
              <span>Join our coummunity to upload your projects</span>
              <i class="bi bi-arrow-right"></i>
            </a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
        <img
          src="{% static 'IndexHome/assets/img/project.svg' %}"
          class="img-fluid"
          alt=""
        />
      </div>
    </div>
  </div>
</section>
{% endblock hero %} {% block owl %}
<header class="section-header">
  <h2>OUR PRODUCT</h2>
  <p>What are you looking for</p>
</header>
<div class="row2-container">
  <div class="box red">
    <h2><a href="">Github Showcase</a></h2>
    <p>
      We host your Github profile, it only cost you a free account on this
      platform
    </p>
    <img src="https://assets.codepen.io/2301174/icon-supervisor.svg" alt="" />
  </div>
  <div class="box blue">
    <h2>Blogs writer</h2>
    <p>
      we provide you the power to follow your passion to write blog by just
      having a account
    </p>
    <img src="https://assets.codepen.io/2301174/icon-karma.svg" alt="" />
  </div>
  <div class="box orange">
    <h2>Team Builder</h2>
    <p>
      Scans our talent network to create the optimal team for your project, this
      product inlclude pricing
    </p>
    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="" />
  </div>
</div>
{% endblock owl %} {% block styling %}
<link href="{% static 'projects/style.css' %}" rel="stylesheet" />
{% endblock styling %}