IndexHome/urls.py
from django.urls import path
from . import views

app_name = 'IndexHome'


urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'check-user/', views.check_user, name="check_user"),
    path(r'verify/<str:mail_hash>/<int:id>/', views.verify,name="verify"),
    path(r'verify/<str:mail_hash>/<int:acc_id>/?request_otp=<str:request_otp>',views.resend_otp, name="verify_resend"),
    path(r'account/login/', views.signin, name="signin"),
    path(r'account/create/', views.signup, name="signup"),
    path(r'account/logout/', views.logout, name="logout"),
    path(r'account/forgot/', views.forgot, name="forgot"),
    path(r'account/forgot/verify', views.forgot_final, name="forgot_final"),
    path(r'playground/', views.playground_timer, name="playground"),
    path(r'subscribe-newsletter/',views.newsletter,name="newsletter"),
    path(r'privacy-policy/',views.privacyPolicy,name="privacy"),
    path(r'contact-us/',views.contact,name="contact"),
    path(r'terms-of-service/',views.termsofService,name="termsofService")
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import HomeView, ArticleDetailView, like_sys, PostByTags, PostByCategory,SearchView
app_name = "blog"
urlpatterns = [
    path('', HomeView.as_view(), name="index"),
    path(r'article/<int:pk>', ArticleDetailView.as_view(), name="blog_details"),
    path(r'like/', like_sys, name="like"),
    path(r'tag/<tag_slug>', PostByTags.as_view(), name='post_list_by_tags'),
    path(r'search/', SearchView.as_view(), name='search_qu'),
    path(r'category/<category_slug>',cache_page(1800)(PostByCategory.as_view()),name="category"),
]

caffeinecode/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import handler500,handler404

urlpatterns = [
    path(r'',include('IndexHome.urls')),
    path(r'admin/', admin.site.urls),
    path(r'blog/',include('blog.urls')),
    path(r'hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path(r'api-auth/', include('rest_framework.urls')),
    path(r'projects/',include("projects.urls")),
    path(r'config/',include("Config.urls")),

]
handler500 = "Config.views.handler500"
handler404 = "Config.views.handler404"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

projects/urls.py
from django.urls import path
from . import views
app_name = "projects"

urlpatterns = [
    path(r'',views.index, name="index")
]

IndexHome/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_verfied = models.BooleanField(default=False)
    account_id = models.BigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    user_email = models.EmailField()
    key = models.TextField(default="empty", max_length=200)
    otp = models.TextField(max_length=6, default="xxxxxx")
    fail_attepmt = models.SmallIntegerField(default=0)
    resend_request = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.user.username

class Newsletter(models.Model):
    subscribe_mail = models.EmailField()

    def __str__(self):
        return self.subscribe_mail

class Notify(models.Model):
    notify_mail = models.EmailField()

    def __str__(self):
        return self.notify_mail

class Contact(models.Model):
    name = models.TextField(max_length=100)
    subject = models.TextField(max_length=100)
    body = models.TextField(max_length=600)
    email = models.EmailField()

    def __str__(self):
        return "Query |" + str(self.pk)

IndexHome/views.py
from requests import request
from . models import Newsletter , Notify,Contact
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import JsonResponse
from django.views.decorators.cache import never_cache
from blog.models import Post,Category
from connectors.Users.UserManager import UserAPI
from connectors.Profiles.ProfileManager import profile_manager
from Config.error import error_message
from django.core.cache import cache


def check_user(request):
    username = request.GET.get('username', None)
    response = {
        'is_taken': User.objects.filter(username__exact=username).exists()
    }
    return JsonResponse(response)

@never_cache
def verify(request, mail_hash, id):
    try:
        profile_connector = profile_manager()
        decrypt_email = profile_connector.get_decrypted_string(mail_hash.encode('utf-8'),id)
        is_user_verify = profile_connector.is_user_verify(decrypt_email.decode())
    except:
        return render(request, "config/error.html", {'error': error_message[0]})
    if request.method == "POST":
        USER_OTP_IN = request.POST.get('Passcode')
        if profile_connector.verify_otp(id, USER_OTP_IN):
            try:
                profile_connector.update_verify(id)
                profile_connector.delete_field(id)
                return redirect("/account/login?redirect-from-verify=True")
            except:
                return render(request, "config/error.html", {'error': error_message[15]})
        else:
            if profile_connector.get_fail(id) < 3:
                profile_connector.add_fail_request(id)
                return render(request, "IndexHome/verify.html", {'otp_fail': True, 'mail': mail_hash, 'email': decrypt_email.decode(), "id": id})
            else:
                profile_connector.reset_fail(id)
                return render(request, 'config/error.html', {'error': error_message[13]})
    else:
        if is_user_verify:
            return render(request, "config/error.html", {'error': error_message[14]})
        else:
            try:
                get_request_from_main = request.session['main_verify']
                if get_request_from_main:
                    profile_connector.generate_only_otp(id)
                    return render(request, "IndexHome/verify.html", {'email': decrypt_email.decode(), 'mail': mail_hash, 'id': id})
                else:
                    return render(request, "IndexHome/verify.html", {'email': decrypt_email.decode(), 'mail': mail_hash, 'id': id})
            except:
                return render(request, "IndexHome/verify.html", {'email': decrypt_email.decode(), 'mail': mail_hash, 'id': id})

@never_cache
def resend_otp(request, mail_hash, acc_id, request_otp):
    if request_otp:
        try:
            profile_connector = profile_manager()
            get_user = profile_connector.search_user_with_id(acc_id)
            email = profile_connector.get_decrypted_string(mail_hash.encode('utf-8'),acc_id)
        except:
            return render(request, "config/error.html", {'error':error_message[0]})
        if get_user.resend_request < 3:
            profile_connector.generate_only_otp(acc_id)
            profile_connector.resend_request(acc_id)
            return render(request, "IndexHome/verify.html", {'mail': mail_hash, 'email': email.decode('utf-8'), 'resend_request': True, 'id': acc_id})
        else:
            profile_connector.reset_resend(acc_id)
            return render(request, 'config/error.html', {'error': error_message[1]})
    else:
        raise Exception("false request")

@never_cache
def signin(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == "POST":
            try:
                sign_in_email = request.POST.get('email', 'default')
                sign_in_password = request.POST.get('password', 'default')
                user_connector = UserAPI()
            except:
                return render('config/error.html', {"error": error_message[2]})
    
            if user_connector.is_user_has_account(sign_in_email) is False:
                return render(request, 'IndexHome/login.html',{"toast":True,"toast_mssg":error_message[3],"simpleMssg":True,"create_account":True})
            else:
                try:
                    user = auth.authenticate(username=user_connector.get_username(sign_in_email), password=sign_in_password)
                    if user is not None and user.is_active:
                        if user_connector.is_user_verify(sign_in_email):
                            auth.login(request, user)
                            try:
                                if request.session["is_redirect"] == True:
                                    return redirect(request.session["to_redirect_url"])
                            except:
                                return redirect('/blog/')
                        else:
                            get_user = user_connector.search_user_with_account_mail(sign_in_email)
                            ver_req = user_connector.get_encrypted_string(sign_in_email,user_connector.get_key(get_user.account_id))
                            request.session['main_verify'] = True
                            return render(request, 'IndexHome/login.html', {"error": error_message[4], "verify_request": True, "mail_en": ver_req.decode('utf-8'), "id": get_user.account_id})
                    else:
                        return render(request, 'IndexHome/login.html',{"toast":True,"toast_mssg":error_message[5],"simpleMssg":True})
                except:
                    return render(request, 'config/error.html', {'error': error_message[6]})
        else:
            try:
                get_redirect_url = request.GET.get("redirect-url")
                get_redirect_verify = request.GET.get("redirect-from-verify")
                request.session['to_redirect_url'] = get_redirect_url
                request.session['is_redirect'] = True
            except:
                request.session['is_redirect'] = False
            if get_redirect_verify == "True":
                return render(request, 'IndexHome/login.html',{"toast":True,"toast_mssg":error_message[18],"simpleMssg":True})
            return render(request, 'IndexHome/login.html')

@never_cache
def signup(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == "POST":
            try:
                data_email = request.POST.get("email")
                data_name = request.POST.get("username")
                data_pass = request.POST.get("password")
                user_connector = UserAPI()
            except:
                return render(request, "config/error.html", {"error": error_message[2]})
            try:
                if user_connector.is_user_has_account(data_email):
                    return render(request, 'IndexHome/signup.html', {"toast":True,"toast_mssg":error_message[7],"simpleMssg":True})
                else:
                    if user_connector.check_same_username(data_name):
                        return render(request, 'config/error.html', {"error": error_message[0]})
                    else:
                        get_params = user_connector.create_account(data_name,data_email,data_pass)
                        return redirect('/verify/{}/{}/'.format(get_params[0].decode('utf-8'),get_params[1]))
            except:
                return render(request,'config/error.html',{'error':error_message[8]})
        else:
            return render(request, 'IndexHome/signup.html')

@never_cache
def logout(request):
    if request.user.is_authenticated and request.user.is_active:
        auth.logout(request)
        return render(request,'IndexHome/index.html',{"toast":True,"toast_mssg":"Logout Successfully!!"})
    else:
        return redirect("/")

@never_cache
def forgot(request):
    if request.method == "POST":
        try:
            user_connector = UserAPI()
            mail_to_request = request.POST.get("email")
            get_user_id = (user_connector.search_user_with_account_mail(mail_to_request)).account_id
            if user_connector.is_user_has_account(mail_to_request):
                if user_connector.is_user_verify(mail_to_request):
                    user_connector.generate_only_otp(get_user_id)
                    request.session['email'] = mail_to_request
                    return render(request, "IndexHome/forgot-final.html")
                else:
                    return render(request, 'IndexHome/forgot.html', {"warning": True, "message": error_message[9]})
            else:
                return render(request, "IndexHome/forgot.html", {"warning": True, "message": error_message[3]})
        except:
            return render(request, "config/error.html", {"error": error_message[16]})
    else:
        return render(request, "IndexHome/forgot.html")

@never_cache
def forgot_final(request):
    try:
        mail = request.session['email']
    except KeyError:
        return render(request, 'config/error.html', {"error":error_message[0]})
    if request.method == "POST":
        try:
            get_code = request.POST.get("code")
            get_new_pass = request.POST.get("password")
            user_connector = UserAPI()
            get_user = user_connector.search_user_with_account_mail(mail)
            if user_connector.verify_otp(get_user.account_id,get_code):
                user_connector.set_user_password(mail,get_new_pass)
                return render(request, 'IndexHome/index.html', {"toast":True,"toast_mssg": error_message[10]})
            else:
                return render(request, 'IndexHome/forgot-final.html', {"error": error_message[11]})
        except:
            return render(request, 'config/error.html', {"error": error_message[12]})
    else:
        return render(request, 'IndexHome/forgot-final.html')

templates/IndexHome/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <title>{% block title %}CaffeineCode{% endblock title %}</title>
        <meta content="" name="description" />
        <meta content="" name="keywords" />
        {% load static %}
        {% load cache %}
        {% cache 400 IndexHomeStaticFileCss %}
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'IndexHome/assets/img/apple-touch-icon.png' %}">
            <link rel="icon" type="image/png" sizes="32x32" href="{% static 'IndexHome/assets/img/favicon-32x32.png' %}">
            <link rel="icon" type="image/png" sizes="16x16" href="{% static 'IndexHome/assets/img/favicon-16x16.png' %}">
            <link rel="manifest" href="{% static 'IndexHome/assets/img/site.webmanifest' %}">
            <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet"/>
            <link href="{% static 'IndexHome/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'IndexHome/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'IndexHome/assets/vendor/aos/aos.css' %}" rel="stylesheet"/>
            <link href="{% static 'IndexHome/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'IndexHome/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'IndexHome/assets/css/style.css' %}" rel="stylesheet"/>
            <script src="{% static 'IndexHome/assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
            <style>
                body {
                    font-family: "Nunito", sans-serif;
                    color: #444444;
                } 
            </style>
            <script>
                function checkDevice(p1, p2) {
                    if(window.innerWidth < 600){
                        alert("Please view this website on computer or laptop for better user experience")
                    }
                }
                $(document).ready(function () {
                    checkDevice();
                });
            </script>
        {% endcache IndexHomeStaticFileCss %}
    </head>
    <body id="bodyscroll">
        <header id="header" class="header fixed-top">
            <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
                <a href="{% url 'IndexHome:index' %}" class="logo d-flex align-items-center">
                <span id="LogoText">CaffeineCode</span>
                </a>
                <nav id="navbar" class="navbar">
                    <ul>
                        <li><a class="nav-link scrollto " href="{% url 'IndexHome:index' %}">Home</a></li>
                        <li><a class="nav-link scrollto" href="#about">About Us</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'projects:index' %}">Projects</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'IndexHome:playground' %}">Playground</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'blog:index' %}">Blog</a></li>
                        <li><a class="nav-link scrollto" href="#contact">Contact {{is_login}}</a></li>
                        {% if user.is_authenticated and user.is_active %}
                            <li><a href="{% url 'IndexHome:logout' %}" role="button" class="getstarted scrollto" style="background: rgb(212, 77, 77)">Logout</a></li>
                            <li><a class="getstarted scrollto" role="button">{{ user.username }}</a></li>
                        {% else %}
                            <li><a class="getstarted scrollto" role="button" href="{% url 'IndexHome:signin' %}">Sign In</a></li>
                        {% endif %}
                    </ul>
                    <i class="bi bi-list mobile-nav-toggle"></i>
                </nav>
            </div>
        </header>

        {% block body %}
        {% endblock body %}
        <div id="toast">
            <i class="bi bi-check"></i>
            <div id="desc">{{toast_mssg}}</div>
        </div>
        {% if toast %}
            {% if simpleMssg %}
                <script>
                    $(document).ready(()=>{
                        launch_toast(true);
                    });
                </script>
            {% else %}
                <script>
                    $(document).ready(()=>{
                        launch_toast(false);
                    });
                </script>
            {% endif %}
        {% endif %}
        
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
        {% cache 400 IndexHomeStaticFileJs %}
            <script src="{% static 'IndexHome/assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
            <script src="{% static 'IndexHome/assets/vendor/aos/aos.js' %}"></script>
            <script src="{% static 'IndexHome/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
            <script src="{% static 'IndexHome/assets/vendor/purecounter/purecounter.js' %}"></script>
            <script src="{% static 'IndexHome/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
            <script src="{% static 'IndexHome/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
            <script src="{% static 'IndexHome/assets/js/core/popper.min.js' %}" type="text/javascript"></script>
            <script src="{% static 'IndexHome/assets/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
            <script src="{% static 'IndexHome/assets/js/main.js' %}"></script>
            <script src="{% static 'IndexHome/assets/js/utils.js' %}"></script>
        {% endcache IndexHomeStaticFileJs %}
    </body>
</html>

templates/IndexHome/forgot-final.html
{% extends 'IndexHome/base_ver.html' %} {% block title %}CaffeineCode - forgotpassword{% endblock title %} 
{% block form %}
<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
        <span class="padding-bottom--15">
            You will recieve a verification code on
            <div class="email" style="color: rgb(112, 112, 233)">
                {{request.session.email}}
            </div>
            Enter that code below and set new password
        </span>
        <br />
        <form id="stripe-login" method="POST" action="{% url 'IndexHome:forgot_final' %}">
            {% csrf_token %}
            <div class="field padding-bottom--24">
                <div class="grid--50-50">
                    <label for="Code">Verification Code</label>
                    <div class="reset-pass">
                        <a href="">Didn't get the code?</a>
                    </div>
                </div>
                <input name="code" title="Enter Code" required spellcheck="false" maxlength="6" style="margin-bottom: 12px" autocomplete="off" autofocus/>
                <div class="grid--50-50">
                    <label for="password">New Password</label>
                </div>
                <input name="password" title="Enter New Password" required spellcheck="false" type="password" autocomplete="off"/>
                {% if error %}
                <div style="color: red; font-size: 15px; margin-top: 4px">
                    {{error}}
                </div>
                {% endif %}
            </div>
            <span style="font-size: 13px; margin-bottom: 12px"><b>Note : Please dont close or refresh this page</b></span>
            <div class="field padding-bottom--24">
                <input type="submit" name="submit" value="Submit" />
            </div>
        </form>
    </div>
</div>
{% endblock form %}

templates/IndexHome/forgot.html
{% extends 'IndexHome/base_ver.html' %} {% block title %}CaffeineCode - forgotpassword{% endblock title %} 
{% block form %}
<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
        <span class="padding-bottom--15">Enter your valid register email address to request forgot password request</span>
        <br/>
        <form id="stripe-login" method="POST" action="{% url 'IndexHome:forgot' %}">
            {% csrf_token %}
            <div class="field padding-bottom--24">
                <div class="grid--50-50">
                    <label for="Email">Email</label>
                </div>
                <input type="email" name="email" required spellcheck="false" autofocus title="Enter Register Email" autocomplete="off"/>
                {% if warning is True %}
                <div style="color: red; font-size: 15px; margin-top: 4px">
                    {{message}}
                </div>
                {% endif %}
            </div>
            <div class="field padding-bottom--24">
                <input type="submit" name="submit" value="Request Forgot Password"/>
            </div>
        </form>
    </div>
</div>
{% endblock form %}

templates/IndexHome/login.html
{% extends 'IndexHome/base_ver.html' %} {% block title %}CaffeineCode - signin{% endblock title %} 
{% block form %}
<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
        <center>
            <span class="padding-bottom--15" style="color: #c2c2c2; font-size: 14px">Sign in with your credentials</span>
        </center>
        <br />
        <form id="stripe-login" method="POST" action="{% url 'IndexHome:signin' %}">
            {% csrf_token %}
            <div class="field padding-bottom--24">
                <div class="grid--50-50">
                    <label for="password">Email</label>
                </div>
                <input name="email" required spellcheck="false" style="margin-bottom: 12px" type="email" autocomplete="off" autofocus title="Your register email"/>
                <div class="grid--50-50">
                    <label for="password">Password</label>
                    <div class="reset-pass">
                        <a href="{% url 'IndexHome:forgot' %}">Forgot Password?</a>
                    </div>
                </div>
                <input name="password" required spellcheck="false" type="password" autocomplete="off" title="Your Login Password"/>
                {% if error %}
                <div style="color: red; font-size: 15px; margin-top: 4px">
                    {{error}}{% if create_account %}
                    <br><a class="ver" href="{% url 'IndexHome:signup' %}"> New to CaffeineCode ? Create Account</a> 
                    {% endif %} 
                    {% if verify_request %}
                    <a class="ver" href="{% url 'IndexHome:verify' mail_hash=mail_en id=id %}" style="color: darkturquoise">click here to verify</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
            <div class="field padding-bottom--24">
                <input type="submit" name="submit" value="Login" />
            </div>
        </form>
    </div>
</div>
{% endblock form %}

templates/IndexHome/signup.html
{% extends 'IndexHome/base_ver.html' %} {% block title %}CaffeineCode - signup{% endblock title %} 
{% block form %}
<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
        <center>
            <span class="padding-bottom--15" style="color: #c2c2c2; font-size: 14px" >Create a new account</span>
        </center>
        <br />
        <form role="form" autocomplete="off" method="POST" action="{% url 'IndexHome:signup' %}" id="stripe-login">
            {% csrf_token %}
            <div class="field padding-bottom--24">
                <div class="grid--50-50">
                    <label for="username">Username</label>
                </div>
                <input id="username" name="username" required spellcheck="false" style="margin-bottom: 4px" type="text" autocomplete="off" pattern="^(?=[a-zA-Z0-9._]{8,20}$)(?!.*[_.]{2})[^_.].*[^_.]$" title="Your username must consist of alphanumeric characters underscore(_),and period(.) underscore and period can't be first or last charcter and next to each other." autofocus/>
                <div id="error" style="color: red; font-size: 15px; margin-bottom: 12px"></div>
                <div class="grid--50-50">
                    <label for="Email">Email</label>
                </div>
                <input name="email" spellcheck="false" style="margin-bottom: 12px" type="email" title="Your Valid Email addrress" autocomplete="off" required/>
                <div class="grid--50-50">
                    <label for="Password">Create Password</label>
                </div>
                <input name="password" required spellcheck="false" type="password" autocomplete="off" title="Create Password"/>
                {% if error %}
                <div style="color: red; font-size: 15px; margin-top: 14px">
                    {{error}}
                </div>
                {% endif %}
            </div>
            <span class="padding-bottom--24"><input type="checkbox" required /> I agree Terms of Service</span>
            <div class="field padding-bottom--24">
                <input class="enableOnInput" type="submit" name="submit" value="Create Account"/>
            </div>
        </form>
    </div>
</div>
<script>
    function delay(callback, ms) {
      var timer = 0;
      return function () {
        var context = this,
          args = arguments;
        clearTimeout(timer);
        timer = setTimeout(function () {
          callback.apply(context, args);
        }, ms || 0);
      };
    }
    $(document).ready(function () {
      $("#username").keyup(
        delay(function (e) {
          $.ajax({
            data: $(this).serialize(),
            url: "{% url 'IndexHome:check_user' %}",
            success: function (response) {
              if (response.is_taken == true) {
                $("#error").html("Username already taken!");
                $(".enableOnInput").prop("disabled", true);
              } else {
                $(".enableOnInput").prop("disabled", false);
                $("#error").html("");
              }
            },
            error: function (response) {
              console.log(response.responseJSON.errors);
            },
          });
          return false;
        }, 500)
      );
    });
</script>
{% endblock form %}

templates/IndexHome/verify.html
{% extends 'IndexHome/base_ver.html' %} {% block title %}CaffeineCode - Verify{% endblock title %} 
{% block form %}
<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
        <span class="padding-bottom--15"
            >
            You will recieve a verification code on
            <div class="email" style="color: rgb(112, 112, 233)">
                {{email}}
            </div>
            Enter that code below.
        </span
            >
        <br />
        <form
            id="stripe-login"
            method="POST"
            action="{% url 'IndexHome:verify' mail_hash=mail id=id %}"
            >
            {% csrf_token %}
            <div class="field padding-bottom--24">
                <div class="grid--50-50">
                    <label for="password">Code</label>
                    <div class="reset-pass">
                        {% if resend_request is not True%}
                        <a
                            href="{% url 'IndexHome:verify_resend' mail_hash=mail  request_otp=True acc_id=id %}"
                            >Resend Verfication Code?</a
                            >
                        {% else %}
                        <div
                            class="resend_func"
                            style="text-align: right; color: rgb(112, 112, 233)"
                            ></div>
                        <script>
                            var timeleft = 180;
                            const url =
                              '<a href="{% url "IndexHome:verify_resend" mail_hash=mail  request_otp=True acc_id=id %}">Resend Verfication Code?</a>';
                            var downloadTimer = setInterval(function () {
                              if (timeleft <= 0) {
                                clearInterval(downloadTimer);
                                $(".resend_func").html(url);
                              } else {
                                $(".resend_func").html(timeleft + " sec");
                              }
                              timeleft -= 1;
                            }, 1000);
                        </script>
                        {% endif %}
                    </div>
                </div>
                <input
                    name="Passcode"
                    required
                    spellcheck="false"
                    maxlength="6"
                    autocomplete="off"
                    autofocus
                    />
                {% if otp_fail is True %}
                <div style="color: red; font-size: 15px; margin-top: 4px">
                    Verification code incorrect!
                </div>
                {% endif %}
                <span style="font-size: 13px; margin-bottom: 12px; user-select: auto;"><b style="user-select: auto;">Note : Please dont close or refresh this page</b></span>
            </div>
            <div class="field padding-bottom--24">
                <input type="submit" name="submit" value="Verify Passcode" />
            </div>
        </form>
    </div>
</div>
{% endblock form %}