IndexHome/urls.py
from django.urls import path
from . import views

app_name = 'IndexHome'


urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'check-user/', views.check_user, name="check_user"),
    path(r'verify/<str:mail_hash>/<int:id>/', views.verify,name="verify"),
    path(r'verify/<str:mail_hash>/<int:acc_id>/?request_otp=<str:request_otp>',views.resend_otp, name="verify_resend"),
    path(r'account/login/', views.signin, name="signin"),
    path(r'account/create/', views.signup, name="signup"),
    path(r'account/logout/', views.logout, name="logout"),
    path(r'account/forgot/', views.forgot, name="forgot"),
    path(r'account/forgot/verify', views.forgot_final, name="forgot_final"),
    path(r'playground/', views.playground_timer, name="playground"),
    path(r'subscribe-newsletter/',views.newsletter,name="newsletter"),
    path(r'privacy-policy/',views.privacyPolicy,name="privacy"),
    path(r'contact-us/',views.contact,name="contact"),
    path(r'terms-of-service/',views.termsofService,name="termsofService")
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import HomeView, ArticleDetailView, like_sys, PostByTags, PostByCategory,SearchView
app_name = "blog"
urlpatterns = [
    path('', HomeView.as_view(), name="index"),
    path(r'article/<int:pk>', ArticleDetailView.as_view(), name="blog_details"),
    path(r'like/', like_sys, name="like"),
    path(r'tag/<tag_slug>', PostByTags.as_view(), name='post_list_by_tags'),
    path(r'search/', SearchView.as_view(), name='search_qu'),
    path(r'category/<category_slug>',cache_page(1800)(PostByCategory.as_view()),name="category"),
]

caffeinecode/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import handler500,handler404

urlpatterns = [
    path(r'',include('IndexHome.urls')),
    path(r'admin/', admin.site.urls),
    path(r'blog/',include('blog.urls')),
    path(r'hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path(r'api-auth/', include('rest_framework.urls')),
    path(r'projects/',include("projects.urls")),
    path(r'config/',include("Config.urls")),

]
handler500 = "Config.views.handler500"
handler404 = "Config.views.handler404"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from hitcount.models import HitCount
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation


class Category(models.Model):
    name = models.CharField(max_length=70)
    cat_img = models.URLField(default="url")

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    blog_snipet = models.CharField(max_length=400)
    title_tag = models.CharField(max_length=20)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(null=True, blank=True)
    date_published = models.DateField(auto_now_add=True)
    entry_img = models.URLField()
    tags = TaggableManager()
    modified = models.DateTimeField(auto_now=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    author_conculsion = models.CharField(max_length=300, default="No Author Review")
    readtime_min = models.IntegerField(default=0)
    editor_choice = models.BooleanField(default=False)
    likes = models.ManyToManyField(User, default=None, blank=True, related_name='post_likes')
    likes_count = models.BigIntegerField(default='0')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

blog/views.py
from django.shortcuts import redirect
from django.views.generic import ListView
from taggit.models import Tag
from hitcount.views import HitCountDetailView
from django.http import JsonResponse
from connectors.Blogs.BlogManager import PostConnector



class HomeView(ListView):

    blog_connector = PostConnector()

    model = blog_connector.post_instance
    template_name = "blog/index.html"
    ordering = ['-date_published', '-hit_count_generic__hits']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['editor'] = self.blog_connector.get_editor_post()
        context['most_like'] = self.blog_connector.get_most_liked_post()
        context['most_used_tag'] = self.blog_connector.get_most_tags_used()
        context['trending_post'] = self.blog_connector.get_most_viewed(context['most_like'])
        context['this_month'] = self.blog_connector.get_this_month()
        context['category'] = self.blog_connector.get_category()
        context['redirect_url'] = self.request.get_full_path()
        return context

class PostByTags(ListView):

    blog_connector = PostConnector()

    def get_queryset(self):
        self.model = self.blog_connector.post_instance
        self.template_name = 'blog/blogtag.html'
        self.tag_slug = self.kwargs['tag_slug']
        self.paginate_by = 5
        self.ordering = ['-hit_count_generic__hits','-likes_count','-date_published'] 
        self.queryset = self.blog_connector.get_PostByTags_model(Tag,tag_slug=self.tag_slug)
        return self.queryset

    def get_context_data(self,**kwargs):
        context = super(PostByTags, self).get_context_data(**kwargs)
        context['most_view'] = self.blog_connector.get_most_viewed(self.queryset)
        context['most_tags'] = self.blog_connector.get_most_tags_used()
        context['category'] = self.blog_connector.get_category()
        context['result'] = True
        context['tag'] = self.tag_slug
        return context

class ArticleDetailView(HitCountDetailView):

    blog_connector = PostConnector()

    model = blog_connector.post_instance
    template_name = 'blog/blogsingle.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        get_all_tags = context['post'].tags.all()
        context['similar_post'] = self.blog_connector.get_similar_post(get_all_tags,self.kwargs.get('pk'))
        context['is_liked'] = self.blog_connector.is_post_like(self.blog_connector.post_instance,self.kwargs['pk'],self.request.user.id)
        context['category'] = self.blog_connector.get_category()
        context['category_post'] = self.blog_connector.get_PostByCategory(context['post'].category).exclude(pk=context['post'].pk)[:3]
        context['redirect_url'] = self.request.get_full_path()
        context['previous_post']  = self.blog_connector.get_previous_post(int(self.kwargs.get('pk')))
        context['next_post'] = self.blog_connector.get_next_post(int(self.kwargs.get('pk')))
        return context

class PostByCategory(ListView):

    blog_connector = PostConnector()

    def get_queryset(self):
        self.model = self.blog_connector.post_instance
        self.template_name = 'blog/category.html'
        self.category_slug = self.kwargs['category_slug']
        self.paginate_by = 5 
        queryset = self.blog_connector.get_PostByCategory(self.category_slug)
        return queryset

    def get_context_data(self,**kwargs):
        context = super(PostByCategory, self).get_context_data(**kwargs)
        context['most_view'] = self.blog_connector.get_most_viewed()
        context['most_tags'] = self.blog_connector.get_most_tags_used()
        context['category'] = self.blog_connector.get_category()
        context['cat'] = self.category_slug
        context['result'] = True
        return context
        
class SearchView(ListView):
    
    blog_connector = PostConnector()

    def get_queryset(self):
        self.model = self.blog_connector.post_instance
        self.template_name = 'blog/search.html'
        self.paginate_by = 5 
        self.query = self.request.GET.get('query')

        try:
            self.search_title = self.request.GET.get('search_title')
        except:
            pass
        try:
            self.search_body =self.request.GET.get('search_body')
        except:
            pass
        try:
            self.category_search = self.request.GET.get('category_selected')
        except:
            pass
        
        def query_none_checker(query_params):
            if query_params is None:
                return False
            else:
                return True
        def category_parser(number):
            category_list = ["Coding","photography","Crypto","Front-End Developer","Django"]
            if number != "None":
                return category_list[int(number)]
            else:
                return None

        self.search_query_set = {
            'query':self.query,
            'search_body':query_none_checker(self.search_body),
            'search_title':query_none_checker(self.search_title),
            'category_text':category_parser(self.category_search)
        }
        self.queryset = self.blog_connector.search(self.search_query_set)
        return self.queryset

    def get_context_data(self,**kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['most_like'] = self.blog_connector.get_most_liked_post()
        context['most_tags'] = self.blog_connector.get_most_tags_used()
        context['category'] = self.blog_connector.get_category()
        context['query_set'] = self.search_query_set
        context['post'] = self.blog_connector.get_recent_post(context['most_like'])
        return context
    
def like_sys(request):
    if request.user.is_authenticated and request.user.is_active:
        if request.method == "POST":
            blog_connector = PostConnector()
            result = ''
            pk_value = int(request.POST.get("postid"))
            post = blog_connector.like(pk_value,request)
            return JsonResponse({"result": post})
    else:
        return redirect("/blog/")

templates/blog/blogsingle.html
{% extends 'blog/base.html' %}
{% block title %}{{post.title_tag}}{% endblock title%} 
{% load hitcount_tags %} 
{% load static %} 


{% block search_block %}
<script>
    $(window).scroll(function () {
      var y_scroll = $(".entry-footer").position().top;
      if ($(this).scrollTop() > y_scroll - 400) {
        $(".social-box").hide(600);
      } 
      else {
        $(".social-box").show(600);
      }
    });
</script>
<div  class="container mb-5" data-aos-duration="600" data-aos="fade-in" style="height: 120px;box-shadow: 0 4px 16px rgb(0 0 0 / 10%);margin-top:80px;">
    <center style="text-align: center; vertical-align: middle; line-height: 120px">ADS TO BE SHOWN HERE</center>
</div>
{% endblock search_block %}

{% block article %}
<article class="entry entry-single">
    <div class="entry-img">
        <img src="{{post.entry_img}}" alt="blog_img" class="img-fluid" />
    </div>
    <a style="font-family: 'Nunito' sans-serif" href="{% url 'blog:blog_details' post.pk %}" class="entry-title">{{post.title}}</a>
    <ul class="entry-meta" style="color: #c2c2c2;list-style-type: none;font-size: 14px;padding-left: 0px;">
        <li>
            <i class="bi bi-eye"></i> {% get_hit_count for post %} |
            <i class="bi bi-calendar2-check"></i> Last updated {{post.modified|date:"F d"}} |
            <i class="bi bi-heart-fill"><span class="like_count">&nbsp;{{post.likes_count}}</span></i>
        </li>
    </ul>
    {% if request.user.is_authenticated and request.user.is_active %}
        <script>
            $(document).on("click", ".like-button", function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: '{% url "blog:like" %}',
                data: {
                postid: $(".like-button").val(),
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
                action: "post",
                },
                success: function (json) {
                $(".like_count").html("&nbsp;" + json["result"]);
                $("#like-icon").toggleClass("bi bi-heart bi bi-heart-fill");
                },
                error: function (xhr, errmsg, err) {},
            });
            });
        </script>
    {% else %}
        <script>
            $(document).on("click", ".like-button", function () {
                window.location.replace(
                    '{% url "IndexHome:signin" %}?redirect-url=' + "{{redirect_url}}"
                );
            });
        </script>
    {% endif %}

    <div class="entry-content">{{post.body|safe}}</div>
    <div class="entry-footer">
        <i class="bi bi-folder"></i>
        <ul class="cats">
            <li><a href="{% url 'blog:category' category_slug=post.category %}">{{post.category}}</a></li>
        </ul>
        <i class="bi bi-tags"></i>
        
        <ul class="tags">
            {% for tag in post.tags.all %}
                <li><a href="{% url 'blog:post_list_by_tags' tag.slug %}">{{tag}}</a></li>
            {% endfor %}
        </ul>
    </div>
</article>

<div class="blog-author d-flex align-items-center">
    <div class="container">
        <div class="row">
                {% if previous_post %}
                    <div class="col">
                        <div class="sidebar" style="box-shadow: none;padding:10px;margin:0px;">
                            <h3 class="sidebar-title mb-4">Previous Blog</h3>
                            <div class="sidebar-item recent-posts">
                                <div class="post-item clearfix mb-4 mt-4">
                                    <img src="{{previous_post.entry_img}}" alt="entry_img">
                                    <h4><a href="{% url 'blog:blog_details' previous_post.pk %}">{{previous_post.title}}</a></h4>
                                    <time>{{previous_post.date_published|date:"F d"}} &bullet; {{previous_post.readtime_min}} min</time>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% if next_post %}
                    <div class="col">
                        <div class="sidebar" style="box-shadow: none;padding:10px;margin:0px;">
                            <h3 class="sidebar-title mb-4">Next Blog</h3>
                            <div class="sidebar-item recent-posts">
                                <div class="post-item clearfix mb-4 mt-4">
                                    <img src="{{ next_post.entry_img}}" alt="entry_img">
                                    <h4><a href="{% url 'blog:blog_details' next_post.pk %}">{{next_post.title}}</a></h4>
                                    <time>{{next_post.date_published|date:"F d"}} &bullet; {{next_post.readtime_min}} min</time>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
        </div>
    </div>
    
</div>

{% endblock article %} 


{% block sidebar %}
    {% if similar_post%}
        <div class="sidebar">
            <h3 class="sidebar-title mb-4">Posts you may like</h3>
            <div class="sidebar-item recent-posts">
                {% for item in similar_post %}
                    <div class="post-item clearfix">
                        <img src="{{item.entry_img}}" alt="entry_img" />
                        <strong><h4><a href="{% url 'blog:blog_details' item.pk %}">{{item.title}}</a></h4></strong>
                        <time>{{item.date_published|date:"F d"}} &bullet; {{item.readtime_min}} min</time>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
<div class="sidebar">
    <h3 class="sidebar-title mb-4">Tags in blog</h3>
    <div class="sidebar-item tags">
        <ul>
            {% for tag in post.tags.all %}
            <li><a href="{% url 'blog:post_list_by_tags' tag.slug %}">{{tag}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="sidebar">Ads To Be shown here</div>
{% endblock sidebar %} 


{% block social-btn %}
<div class="social-box" style="height: fit-content">
    <div class="sticky-container">
        <div class="container" style="justify-content: center; padding: 5px">
            {% if request.user.is_authenticated %} {% if is_liked %}
            <button class="like-button" title="Like" value="{{post.pk}}">
                <h5><i id="like-icon" class="bi bi-heart-fill"></i></h5>
            </button>
            {% else %}
            <button class="like-button" value="{{post.pk}}">
                <h5><i id="like-icon" class="bi bi-heart"></i></h5>
            </button>
            {% endif %} {% else %}
            <button class="like-button" value="{{post.pk}}">
                <h5><i id="like-icon" class="bi bi-heart"></i></h5>
            </button>
            {% endif %}
        </div>
    </div>
    <div class="sticky-container" style="margin-top: 40px; background: #3b5999">
        <div class="container" style="justify-content: center; padding: 5px">
            <h5><i class="bi bi-bookmarks"></i></h5>
        </div>
    </div>
</div>
{% endblock social-btn %} 

{% block pagination %}
{% endblock pagination %} 


{% block recent %}
    {% if category_post %}
        <section id="recent-blog-posts" class="recent-blog-posts">
            <div class="container aos-init aos-animate" data-aos="fade-up">
                <header class="section-header">
                    <p>Posts with same category</p>
                </header>
                <div class="row">
                    {% for cat_post in category_post %}
                        <div class="col-lg-4">
                            <div class="post-box">
                                <div class="post-img">
                                    <img src="{{cat_post.entry_img}}" class="img-fluid" alt="category_img"/>
                                </div>
                                <span class="post-date">{{cat_post.date_published}}</span>
                                <h3 class="post-title">{{cat_post.title}}</h3>
                                <a href="{% url 'blog:blog_details' cat_post.pk %}" class="readmore stretched-link mt-auto"><span>Read More</span><i class="bi bi-arrow-right"></i></a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}
{% endblock recent %} 

{% block category %} 
    {% for name in category %}
        <li>
            <a href="{% url 'blog:category' category_slug=name.name %}">{{name.name}}</a>
        </li>
    {% endfor %} 
{% endblock category %}

templates/blog/blogtag.html
{% extends 'blog/base.html' %} 
{% block title %}CaffeineCode - Blogs{% endblock title%} 
{% load hitcount_tags %} 
{% load static %} 
{% block search_block %}
<div class="container mb-5" data-aos-duration="600" data-aos="fade-in" style="height: 120px; box-shadow: 0 4px 16px rgb(0 0 0 / 10%);margin-top:80px;">
    <center style="text-align: center; vertical-align: middle; line-height: 120px">
        ADS TO BE SHOWN HERE
    </center>
</div>
{% if result %}
<div class="container mb-4" data-aos="fade-up">
    <h2 style="margin-top: 2em">
        Blogs tagged with <span style="background: #0257ee;color: white;padding: 8px;border-radius: 5px;">{{tag}}</span>
    </h2>
</div>
<br />
{% endif %} 
{% endblock search_block %} 
{% block article %} 
{% if forloop.counter == 4 %}
<article class="entry" style="height: 120px; width: 100%">
    <center>ADS TO BE SHOWN HERE</center>
</article>
{% endif %} 
{% for post in object_list %}
<article class="entry">
    <div class="entry-img">
        <img src="{{post.entry_img}}" alt="entry_img" class="img-fluid" />
    </div>
    <h2 class="entry-title">
        <a href="{% url 'blog:blog_details' post.pk %}">{{post.title}}</a>
    </h2>
    <div class="entry-meta">
        <ul>
            <li class="d-flex align-items-center">
                <i class="bi bi-person"></i>
                <a href="blog-single.html">{{post.author}}</a>
            </li>
            <li class="d-flex align-items-center">
                <i class="bi bi-clock"></i>{{post.date_published|date:"F d"}}
            </li>
            <li class="d-flex align-items-center">
                <i class="bi bi-eye"></i>{% get_hit_count for post %}
            </li>
            <li class="d-flex align-items-center">
                <i class="bi bi-heart-fill"></i>{{post.likes_count}}
            </li>
        </ul>
    </div>
    <div class="entry-content">
        <p>{{post.blog_snipet| slice:":200"}}</p>
        <div class="read-more">
            <a href="{% url 'blog:blog_details' post.pk %}">Read More</a>
        </div>
    </div>
</article>
{% empty %}
<article class="entry">
    <div class="entry-img">
        <img src="{% static 'IndexHome/assets/img/empty.png' %}" height="300px" class="img-fluid"/>
    </div>
    <div class="entry-title" style="text-align: center; color: rgb(240, 75, 75)">
        No posts tagged with "{{tag}}"
    </div>
</article>
{% endfor %} {% endblock article %} {% block pagination %} 
{% if result %}
<nav aria-label="Page navigation">
    <ul class="paginationm mb-5">
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %} 
        {% for n in posts.paginator.page_range %} 
        {% if posts.number == n %}
            <li class="page-item active">
                <span class="page-link">{{ n }}<span class="sr-only"></span></span>
            </li>
        {% elif n > posts.number|add:'-3' and n < posts.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ n }}">{{ n }}</a>
            </li>
        {% endif %} {% endfor %} 
        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %} 
{% endblock pagination %}
 
{% block sidebar %} 
{% if most_view %}
<div class="sidebar">
    <h3 class="sidebar-title mb-4">Recent Posts</h3>
    <div class="sidebar-item recent-posts">
        {% for item in most_view %}
        <div class="post-item clearfix">
            <img src="{{item.entry_img}}" alt="most_view_entry_img" />
            <h4>
                <a href="{% url 'blog:blog_details' item.pk %}">{{item.title}}</a>
            </h4>
            <time>{{item.date_published|date:"F d"}}</time>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="sidebar">
    <h3 class="sidebar-title mb-4">Popular Tags</h3>
    <div class="sidebar-item tags">
        <ul>
            {% for used_tag in most_tags %}
                <li>
                    <a href="{% url 'blog:post_list_by_tags' used_tag.slug %}">{{used_tag}}</a>
                </li>
            {%endfor%}
        </ul>
    </div>
</div>
<div class="sidebar">Ads to be shown here</div>
{% endblock sidebar %} 

{% block category %} 
{% for name in category %}
    <li>
        <a href="{% url 'blog:category' category_slug=name.name %}">{{name.name}}</a>
    </li>
{% endfor %} 
{% endblock category %}

templates/blog/category.html
{% extends 'blog/base.html' %} {% block title %}CaffeineCode - Blogs{% endblock title %} 
{% load hitcount_tags %} {% load static %} {% block search_block %}
<div class="container mb-5" data-aos-duration="600" data-aos="fade-in" style="height: 120px; box-shadow: 0 4px 16px rgb(0 0 0 / 10%);margin-top: 80px">
    <center style="text-align: center; vertical-align: middle; line-height: 120px">
        ADS TO BE SHOWN HERE
    </center>
</div>
{% if result %}
<div class="container mb-4" data-aos="fade-up">
    <h2 style="margin-top: 2em">
        Search in
        <span style="background: #0257ee;color: white;padding: 8px;border-radius: 5px;">{{cat}}</span>
    </h2>
</div>
<br />
{% endif %} 
{% endblock search_block %} 

{% block article %} 
{% if forloop.counter == 4 %}
<article class="entry" style="height: 120px; width: 100%">
    <center>ADS TO BE SHOWN HERE</center>
</article>
{% endif %}
{% for post in object_list %}
<article class="entry">
    <div class="entry-img">
        <img src="{{post.entry_img}}" alt="entry_img" class="img-fluid" />
    </div>
    <h2 class="entry-title">
        <a href="{% url 'blog:blog_details' post.pk %}">{{post.title}}</a>
    </h2>
    <div class="entry-meta">
        <ul>
            <li class="d-flex align-items-center">
                <i class="bi bi-person"></i>
                <a href="blog-single.html">{{post.author}}</a>
            </li>
            <li class="d-flex align-items-center">
                <i class="bi bi-clock"></i>{{post.date_published|date:"F d"}}
            </li>
            <li class="d-flex align-items-center">
                <i class="bi bi-eye"></i>{% get_hit_count for post %}
            </li>
            <li class="d-flex align-items-center">
                <i class="bi bi-heart-fill"></i>{{post.likes_count}}
            </li>
        </ul>
    </div>
    <div class="entry-content">
        <p>{{post.blog_snipet| slice:":200"}}</p>
        <div class="read-more">
            <a href="{% url 'blog:blog_details' post.pk %}">Read More</a>
        </div>
    </div>
</article>
{% empty %}
<article class="entry">
    <div class="entry-img">
        <img src="{% static 'IndexHome/assets/img/empty.png' %}" height="300px" class="img-fluid"/>
    </div>
    <div class="entry-title" style="text-align: center; color: rgb(240, 75, 75)">
        No post in {{cat}}
    </div>
</article>
{% endfor %} 
{% endblock article %}

{% block pagination %} 
{% if result %}
<nav aria-label="Page navigation">
    <ul class="paginationm mb-5">
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %} 
        {% for n in posts.paginator.page_range %} 
        {% if posts.number == n %}
        <li class="page-item active">
            <span class="page-link">{{ n }}<span class="sr-only"></span></span>
        </li>
        {% elif n > posts.number|add:'-3' and n < posts.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
        </li>
        {% endif %} 
        {% endfor %} 
        {% if posts.has_next %}
        <li class="page-item">
            <a
                class="page-link"
                href="?page={{ posts.paginator.num_pages }}"
                aria-label="Next"
                >
            <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %} 
{% endblock pagination %} 

{% block sidebar %} 
{% if most_view %}
<div class="sidebar">
    <h3 class="sidebar-title mb-4">Most Viewed Posts</h3>
    <div class="sidebar-item recent-posts">
        {% for item in most_view %}
        <div class="post-item clearfix">
            <img src="{{item.entry_img}}" alt="most_view_entry_img" />
            <h4>
                <a href="{% url 'blog:blog_details' item.pk %}">{{item.title}}</a>
            </h4>
            <time>{{item.date_published|date:"F d"}}</time>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="sidebar">
    <h3 class="sidebar-title mb-4">Popular Tags</h3>
    <div class="sidebar-item tags">
        <ul>
            {% for used_tag in most_tags %}
            <li>
                <a href="{% url 'blog:post_list_by_tags' used_tag.slug %}">{{used_tag}}</a>
            </li>
            {%endfor%}
        </ul>
    </div>
</div>
<div class="sidebar">Ads to be shown here</div>
{% endblock sidebar %} 
{% block category %} 
{% for name in category %}
<li>
    <a href="{% url 'blog:category' category_slug=name.name %}">{{name.name}}<span></span></a>
</li>
{% endfor %} 
{% endblock category %}